# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Migration App Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'migration-v0.0.1' 

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Extract clean tag name
        id: vars
        run: |
          RAW_TAG=${{ github.event.inputs.version }}
          CLEAN_TAG=${RAW_TAG#migration-}
          echo "RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "CLEAN_TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Build Linux amd64 binary
        run: |
          cd migration-mysql-app
          GOOS=linux GOARCH=amd64 go build -o migration-mysql-app-linux-amd64-${CLEAN_TAG}

      - name: Build macOS arm64 binary
        run: |
          cd migration-mysql-app
          GOOS=darwin GOARCH=arm64 go build -o migration-mysql-app-darwin-arm64-${CLEAN_TAG}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RAW_TAG }}
          files: |
            migration-mysql-app/migration-mysql-app-linux-amd64-${{ env.CLEAN_TAG }}
            migration-mysql-app/migration-mysql-app-darwin-arm64-${{ env.CLEAN_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
